// Percorso completo "Azienda" (Property + RC) nel browser, fino al riepilogo. Uso: node prova_property.js [larghezza]
const { chromium } = require('playwright');
const LARG = Number(process.argv[2] || 1366), MOBILE = LARG < 900, DIR = MOBILE ? 'prove/tel' : 'prove/pc';
(async () => {
  const b = await chromium.launch();
  const pg = await (await b.newContext({ viewport: { width: LARG, height: MOBILE ? 844 : 860 }, deviceScaleFactor: MOBILE ? 2 : 1, isMobile: MOBILE, hasTouch: MOBILE, locale: 'it-IT' })).newPage();
  const err = []; pg.on('pageerror', e => err.push(e.message));
  await pg.goto('http://localhost:8765/index.html'); await pg.evaluate(() => Pratiche.tutte().forEach(p => Pratiche.elimina(p.id))); await pg.reload();
  const sc = (c, v) => pg.click(`[data-campo=${c}][data-v="${v}"]`), mu = v => pg.click(`[data-multi="${v}"]`);
  const larghe = [];
  const av = async () => { const w = await pg.evaluate(() => document.documentElement.scrollWidth); if (w > LARG) larghe.push((await tit()) + ' ' + w + 'px'); await pg.click('[data-az=avanti]'); await pg.waitForTimeout(80); };
  const fill = async (id, v) => { await pg.fill('#f_' + id, v); await pg.locator('#f_' + id).blur(); await pg.waitForTimeout(30); };
  const tit = () => pg.textContent('.passo-titolo');
  const errori = () => pg.$$eval('.errore', e => e.map(x => (x.closest('[data-box]') || {}).dataset?.box + ':' + x.textContent));
  await pg.click('[data-az=preventivo]'); await pg.click('[data-nodo=az]'); await pg.click('[data-nodo=az-re]'); await pg.click('[data-prodotto=commercio]');
  await fill('nome', 'Ferramenta Rossi Srl'); await fill('piva', '01234567890'); await fill('email', 'info@ferramentarossi.it'); await fill('tel', '0332123456'); await sc('docTipo', 'no'); await av();
  await fill('attivita', 'Ferramenta con posa di serramenti presso i clienti'); await fill('annoCost', '1998'); await fill('addetti', '6'); await fill('fatturato', '1200000');
  await sc('controllata', 'no'); await sc('controlla', 'no'); await sc('estero', 'no'); await sc('noSanzioni', 'si'); await av();
  for (const g of ['incendio', 'furto', 'rc', 'tutela']) await mu(g);
  await sc('titoloFabb', 'affitto'); await fill('sMacchinari', '150000'); await fill('sMerci', '200000'); await fill('sFurto', '30000');
  await sc('massimaleRC', '3'); await sc('rco', 'si'); await sc('altraPolizza', 'no'); await av();
  console.log('dopo Garanzie →', await tit(), await errori());
  await sc('piuUbicazioni', 'no'); await sc('ubStessoIndirizzo', 'si'); await sc('zona', 'periferia'); await sc('configurazione', 'unico');
  await fill('annoFabb', '1985'); await fill('supCoperta', '400'); await sc('piani', '1-3'); await sc('interrati', 'no');
  await sc('struttura', 'laterizi'); await sc('tetto', 'tegole'); await sc('fabbTipo', 'si'); await sc('fotovoltaico', 'tetto'); await av();
  console.log('dopo Ubicazione →', await tit(), await errori());
  await sc('infiammabili', 'assenti'); await sc('impElettrici', 'buoni'); await mu('tettoie'); await mu('insegne'); await sc('refrigerate', 'no'); await sc('stagionali', 'si'); await fill('stagionaliPeriodo', 'marzo-giugno'); await av();
  console.log('dopo Rischio →', await tit(), await errori());
  await sc('estintori', 'si'); await sc('cpi', 'nonSoggetta'); await sc('recinzione', 'assente'); await sc('allarme', 'si'); await sc('allarmeColl', 'vigilanza');
  await sc('video', 'no'); await sc('vigilanza', 'no'); await sc('custode', 'no'); await sc('chiusure', 'rafforzati'); await av();
  console.log('dopo Protezioni →', await tit(), await errori());
  await mu('posa'); await mu('trasporto'); await av();
  console.log('arrivo a →', await tit());
  const sel = await pg.$$eval('[data-box=garOpz] [aria-pressed=true]', e => e.map(x => x.innerText.replace(/\s*consigliata/, '')));
  console.log('garanzie spuntate in automatico:', sel);
  console.log('avviso sconti:', await pg.textContent('[data-avviso=garOpz]'));
  await pg.evaluate(() => scrollTo(0, 0)); await pg.screenshot({ path: `${DIR}/property-aggiuntive.png`, fullPage: !MOBILE });
  await fill('vFotov', '25000'); await fill('vAumento', '80000'); await av();
  console.log('dopo Aggiuntive →', await tit(), await errori());
  await sc('sinistri5', 'no'); await sc('stornate', 'no'); await sc('procedure', 'no'); await av();
  await sc('mup', 'si'); await sc('privacy', 'si'); await av();
  const t = await pg.textContent('#vista');
  console.log('riepilogo:', /Ferramenta Rossi/.test(t), '| furto 30.000:', /30\.000/.test(t), '| RC 3 milioni:', /3 milioni/.test(t), '| lavori presso terzi:', /Lavori presso terzi/.test(t));
  console.log('passi più larghi dello schermo:', larghe.length ? larghe : 'nessuno', '| larghezza finale:', await pg.evaluate(() => document.documentElement.scrollWidth), '| errori pagina:', err);
  await b.close();
})();
